api/blueprints/authentication.py
import os
from flask import Blueprint, session, redirect, url_for, request
from six.moves.urllib.parse import urlencode
from api.classes.oauth import Authentication

authentication = Blueprint('authentication', __name__)


@authentication.route('/callback/')
def callback():
    """
    Define a function to handle auth callbacks.
    :return redirect to dashboard.
    """
    # Handles response from token endpoint
    access_token = Authentication.auth0.authorize_access_token()
    resp = Authentication.auth0.get('userinfo')
    userinfo = resp.json()

    # Store the user information in flask session.
    session['jwt_payload'] = userinfo
    session["scopes"] = access_token["scope"].split(' ')
    session['profile'] = {
        'user_id': userinfo['sub'],
        'name': userinfo['name'],
        'picture': userinfo['picture']
    }
    redirect_uri = request.args.get("redirect_uri") or url_for('website.index')
    return redirect(redirect_uri)


@authentication.route('/login/')
def login():
    """
    Endpoint to authenticate users with auth0.
    :return: Redirect to auth0 login page.
    """
    redirect_uri = url_for('authentication.callback', _external=True, redirect_uri=request.args.get("redirect_uri"))
    return Authentication.auth0.authorize_redirect(redirect_uri=redirect_uri,
                                                   audience='https://uh-dns.eu.auth0.com/userinfo')


@authentication.route('/signup/')
def signup():
    """
    Endpoint to authenticate users with auth0.
    :return: Redirect to auth0 signup page.
    """
    return Authentication.auth0.authorize_redirect(redirect_uri=url_for('authentication.callback', _external=True),
                                                   audience='https://uh-dns.eu.auth0.com/userinfo',
                                                   signUp="true")


@authentication.route('/logout/')
def logout():
    """
    Logout a user and delete session data.
    :return:
    """
    session.clear()
    params = {'returnTo': url_for('website.index', _external=True), 'client_id': 'MR3c9T4pmw3wKXm2YfMloTKpeiVhQgpQ'}
    return redirect(Authentication.auth0.api_base_url + '/v2/logout?' + urlencode(params))

api/blueprints/website.py
from flask import Blueprint, render_template, request, abort, flash, redirect, url_for
from api.decorators.authentication import requires_auth
from api.classes.db import db, get_root_domain
from api.classes.recordtype import RecordType
from api.classes.customjsonencoder import CustomJSONEncoder
from api.classes.livechecker import LiveChecker
from api.classes.errors import ControlledException
from api.classes.status import ReturnCode
from api import menu, current_user
from flask_wtf import FlaskForm
from wtforms import *
from wtforms.validators import InputRequired, Length
import json, validators, tldextract


website = Blueprint('website', __name__)


def should_return_JSON():
    return "application/json" in request.accept_mimetypes and \
        not "text/html" in request.accept_mimetypes


@website.route("/")
@menu.register_menu(website, ".", "Home")
def index():
    return render_template("index.html")


@website.route("/domains/")
@menu.register_menu(website, ".domains", "Domains")
@requires_auth("user")
def domains():
    return render_template("domains.html", domains=db.get_root_domains(current_user.user_id))


@website.route("/domains/<domain>/")
@requires_auth("user")
def domain_records(domain):
    domain = get_root_domain(domain)
    records = db.get_records_for_root_domain(domain, current_user.user_id)
    if len(records) == 0:
        abort(404)

    root_record = None
    for record in records:
        if record["domain"] == domain:
            root_record = record

    def getRTypes(record):
        ret = [{ "name": key[0].name, "data": record[key[0].name]} for key in RecordType.choices() if key[0].name in record]
        return ret

    return render_template("records.html", records=records, getRTypes=getRTypes, \
            domain=domain, root_record=root_record)

def Domain(form, field):
    data = field.data
    if data[-1:] == ".":
        data = data[:-1]

    if validators.domain(data) != True:
        raise ValidationError("Invalid domain name")

class DomainForm(FlaskForm):
    domain = StringField("Domain", [InputRequired(), Length(1, 40), Domain])
    submit = SubmitField("Save")


@website.route("/domains/new/", methods=["GET", "POST"])
@requires_auth("user")
def domain_new():
    form = DomainForm(formdata=request.form)
    if form.validate_on_submit():
        domain = get_root_domain(form.domain.data)
        records = db.get_records_for_root_domain(domain, current_user.user_id)
        if domain[-1:] != ".":
            domain = domain + "."

        if len(records) > 0:
            flash("Domain already exists", "warning")
        elif len(db.get_live_records_by_domain(domain)) > 0:
            flash("Domain already created by another user", "warning")
        else:

            item = {
                "domain":  domain,
                "user_id": current_user.user_id,
                "live" : False,
                "NS": { "ttl": 3600, "value": ["ns1.uh-dns.com.", "ns2.uh-dns.com."] },
                "SOA": { "ttl": 900, "times": [2018122100,7200,900,1209600,86400], "mname": "ns1.uh-dns.com.", "rname": "engineering.ultra-horizon.com." },
            }

            assert(RecordType.NS.check_structure(item["NS"]))
            assert(RecordType.SOA.check_structure(item["SOA"]))

            db.put_record(item)

            return redirect(url_for("website.domain_records", domain=domain[:-1]))

    return render_template("domain_new.html", form=form)


@website.route("/domains/<domain>/check/", methods=["POST"])
@requires_auth("user")
def domain_check(domain):
    if domain != get_root_domain(domain):
        abort(404)
    root = db.get_record(domain, current_user.user_id)
    if root is None:
        abort(404)

    try:
        if not LiveChecker.check(root, domain):
            raise ControlledException(ReturnCode.UNKNOWN)

        root["live"] = True
        db.put_record(root)
    except ControlledException as e:
        flash("Failed. Error: " + e.status.name, "danger")

    return redirect(url_for("website.domain_records", domain=domain))

class RecordForm(FlaskForm):
    domain = StringField("Hostname", [InputRequired(), Length(1, 40), Domain])
    type   = SelectField("Type", [InputRequired()], choices=RecordType.choices(), coerce=RecordType.coerce, default=RecordType.A)
    ttl    = IntegerField("TTL", default=10)
    value  = StringField("Value", [Length(0, 1000)])
    mname  = StringField("MNAME (Primary Master Nameserver)", [Length(0, 1000)])
    rname  = StringField("RNAME (Email address with @ replaced with .)", [Length(0, 1000)])
    submit = SubmitField("Save")


def do_domain_records_new(form):
    record_entry = {}

    type = form.type.data.name
    if type == "CNAME":
        record_entry["domain"] = form.value.data.strip()
    elif type == "TXT":
        record_entry["value"] = form.value.data.strip()
    else:
        record_entry = json.loads(form.value.data)

    record_entry["ttl"] = form.ttl.data

    if type == "SOA":
        record_entry["mname"] = form.mname.data
        record_entry["rname"] = form.rname.data

    # Validate record entry
    if not form.type.data.check_structure(record_entry):
        return False, "Invalid record entry"

    # Retrieve record
    if form.domain.data[-1:] != ".":
        form.domain.data = form.domain.data + "."

    item = db.get_record(form.domain.data, current_user.user_id)
    if item is None:
        item = {
            "user_id": current_user.user_id,
            "domain": form.domain.data,
            "live": False
        }

    suc, msg = form.type.data.validate_put(item, record_entry)
    if not suc:
        return False, msg

    # Add
    item[form.type.data.name] = record_entry

    # Check whether subdomain should be marked live.
    root_domains = db.get_root_domains(current_user.user_id)
    domain = form.domain.data
    while tldextract.extract(domain).subdomain != "":  # Perform recursive search up to the TLD.
        domain = domain.split(".", 1)[1:][0]
        if domain in root_domains:
            record = db.get_record(domain, current_user.user_id)
            item["live"] = record["live"]

    db.put_record(item)
    return True, None


@website.route("/domains/<domain>/<hostname>/delete/", methods=["POST"])
@website.route("/domains/<domain>/<hostname>/<record>/delete/", methods=["POST"])
@requires_auth("user")
def domain_record_delete(domain, hostname, record=None):
    item = db.get_record(hostname, current_user.user_id)
    if item is None:
        abort(404)

    if record is None:
        if get_root_domain(hostname) == hostname:
            db.put_record({
                "domain": hostname,
                "user_id": current_user.user_id,
                "live": False,
                "NS": {"ttl": 3600, "value": ["ns1.uh-dns.com.", "ns2.uh-dns.com."]},
                "SOA": {"ttl": 900, "times": [2018122100, 7200, 900, 1209600, 86400], "mname": "ns1.uh-dns.com.", "rname": "engineering.ultra-horizon.com."},
            })
            flash("Cleared " + hostname + " (can't delete root domain!)", "success")
        else:
            db.delete_record(hostname, current_user.user_id)
            flash("Deleted " + hostname, "success")

    else:
        record = RecordType.get(record)
        if record is None:
            abort(404)

        del item[record.name]
        db.put_record(item)

        flash("Deleted " + record.name + " from " + hostname, "success")

    return redirect(url_for("website.domain_records", domain=domain))


@website.route("/domains/<domain>/new/", methods=["GET", "POST"])
@website.route("/domains/<domain>/<hostname>/new/", methods=["GET", "POST"])
@website.route("/domains/<domain>/<hostname>/<record>/edit/", methods=["GET", "POST"])
@requires_auth("user")
def domain_record_newedit(domain, hostname=None, record=None):
    form = RecordForm(formdata=request.form)

    if record is not None:
        form.domain.data = hostname
        form.type.data = RecordType.get(record)
        if form.type.data is None:
            abort(404)

    if request.method == "GET":
        form.domain.data = hostname or domain
        if form.domain.data[-1:] != ".":
            form.domain.data = form.domain.data + "."

        if record is not None:
            item = db.get_record(form.domain.data, current_user.user_id)
            if item is None:
                abort(404)

            type = form.type.data

            if type.name in item:
                form.ttl.data = item[type.name]["ttl"]
                form.mname.data = item[type.name].get("mname")
                form.rname.data = item[type.name].get("rname")

                if type == RecordType.CNAME:
                    form.value.data = item[type.name]["domain"]
                elif type == RecordType.TXT:
                    form.value.data = item[type.name]["value"]
                else:
                    form.value.data = json.dumps(item[type.name], cls=CustomJSONEncoder)

    elif form.validate_on_submit():
        suc, msg = do_domain_records_new(form)
        if suc:
            return redirect(url_for("website.domain_records", domain=get_root_domain(domain)))
        elif msg:
            flash(msg, "danger")

    return render_template("record_newedit.html", form=form, \
        domain=domain, hostname=hostname, record=record, is_edit=record is not None)

api/templates/base.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="icon" href="/static/favicon.ico">

	<title>{% block title %}title{% endblock %} - UH DNS</title>

	<link href="/static/bootstrap.css" rel="stylesheet">
	<link href="/static/style.css" rel="stylesheet">
</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
		<div class="container">
            <a href="/" class="navbar-brand"><img id="logo" src="/static/uh-dns.svg" alt="UH DNS"></a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarsExampleDefault">
				<ul class="navbar-nav mr-auto">
				{% for item in current_menu.children recursive %}
					{% if item.visible %}
						<li class="nav-item{% if item.children %} dropdown{% endif %}">
							<a class="nav-link" href="{{ item.url }}">
								{{ item.text }}
								{% if item.children %}
									<span class="caret"></span>
								{% endif %}
							</a>
							{% if item.children %}
							<ul class="dropdown-menu" role="menu">
								{{ loop(item.children) }}
							</ul>
							{% endif %}
						</li>
					{% endif %}
				{% endfor %}
				</ul>

				<ul class="navbar-nav my-2 my-lg-0">
				{% if current_user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link" href="#">{{ current_user.fullname }}</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('authentication.logout') }}">Log Out</a>
					</li>
				{% else %}
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('authentication.login') }}">Login</a>
					</li>
				{% endif %}
				</ul>
			</div>
			</div>
	</nav>

	{% block flash_messages %}
		{%- with messages = get_flashed_messages(with_categories=true) -%}
		{% if messages %}
			<ul id="alerts">
				{% for category, message in messages %}
				<li class="alert alert-{{category}} container">
					<span class="icon_message"></span>

					{{ message|safe }}

					<div style="clear: both;"></div>
				</li>
				{% endfor %}
			</ul>
		{% endif %}
		{%- endwith %}
	{% endblock %}

	<main role="main">
		{% block main %}
			<article class="container my-4">
				{% block content %}
				{% endblock %}
			</article>
		{% endblock %}
	</main>

	<footer class="container">
		<hr>
		<p>© 2019, ULTRA HORIZON CONSULTANCY LIMITED</p>
	</footer>

	<!-- Bootstrap core JavaScript
	================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="/static/jquery.min.js"></script>
	<script src="/static/popper.min.js"></script>
	<script src="/static/bootstrap.min.js"></script>

	{% block scriptextra %}{% endblock %}
</body>
</html>

api/templates/domain_new.html
{% extends "base.html" %}

{% block title %}
Add Domain
{% endblock %}

{% block content %}
<h1>Add Domain</h1>

{% from "macros/forms.html" import render_field, render_submit_field %}
<form method="POST" action="" enctype="multipart/form-data" style="display:inline;">
	{{ form.hidden_tag() }}
	{{ render_field(form.domain) }}
	{{ render_submit_field(form.submit) }}
</form>

{% endblock %}

api/templates/domains.html
{% extends "base.html" %}

{% block title %}
Domains
{% endblock %}

{% block content %}
<a class="float-right btn btn-primary" href="{{ url_for('website.domain_new') }}">New</a>
<h1>Domains</h1>


<div class="list-group">
	{% for d in domains %}
		<a href="{{ url_for('website.domain_records', domain=d) }}"
				class="list-group-item list-group-item-action">
			{{ d }}
		</a>
	{% else %}
		<div class="list-group-item"><i>No sites found.</i></div>
	{% endfor %}
</div>
{% endblock %}
<!doctype html>

api/templates/index.html
{% extends "base.html" %}

{% block title %}
    Welcome
{% endblock %}

{% block main %}
<div class="jumbotron">
	<div class="container">
		<h1 class="display-3">Welcome to a new type of DNS</h1>
		<p>UH DNS is a highly scalable and fast authoritative DNS service. The domain name system is  an integral part of the Internet and is responsible for a wide variety of tasks. Ensuring that your domain's DNS records are hosted by a performant and reliable provider can directly impact the uptime and performance of your services. UH DNS is a new service which combats some of the shortcomings of traditional DNS providers.</p>
		<p><a class="btn btn-primary btn-lg" href="signup" role="button">Sign Up</a></p>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-4">
			<h2>Fast</h2>
			<p>UH DNS was engineered for speed from the ground up. It is built upon the fibre backbone of some of the largest data centres in the world. Low latency connections coupled with our efficient distributed record database ensures that DNS queries are answered as fast as possible. No more waiting for zone transfers and propagation; our authoritative servers update instantly.</p>
		</div>
		<div class="col-md-4">
			<h2>Scalable</h2>
			<p>Scalability is at the heart of UH DNS. Unlike traditional DNS servers which rely on horizontally scaled servers or zone transfers between multiple servers. Our service utilises a scalable distributed record database. Load balancers automatically distribute your domain's DNS requests to active servers which are created and destroyed based on demand.</p>
		</div>
		<div class="col-md-4">
			<h2>Open Source</h2>
			<p>At Ultra Horizon, we believe in the open source software model. We want our customers to be able to verify that their records are hosted, queried and answered as we say. Furthermore, we want to provide you with a service that you can depend on. If a new feature is desired or a bug is found you can submit it straight to us. <br>
                <a href="https://github.com/jwsi/dns-server">Server Repo</a>
                 |
                <a href="https://github.com/jwsi/dns-website">Website Repo</a></p>
		</div>
	</div>
</div>
{% endblock %}
<!doctype html>

api/templates/record_newedit.html
{% extends "base.html" %}

{% block title %}
Welcome
{% endblock %}

{% block content %}
<h1>{% if is_edit %}Edit{% else %}Add{% endif %} Record</h1>

{% if not is_edit %}
<p>
	<b>Warning:</b> this will delete any records of the same type.
</p>
{% endif %}

{% from "macros/forms.html" import render_field, render_submit_field, render_select_field %}
<form method="POST" action="" enctype="multipart/form-data" style="display:inline;">
	{{ form.hidden_tag() }}
	<div class="row">
	{{ render_field(form.domain, class_="col-sm-4", readonly=is_edit) }}
	{{ render_select_field(form.type, class_="col-sm-4", readonly=is_edit) }}
	{{ render_field(form.ttl, class_="col-sm-4") }}
	</div>
	<div class="row soa" style="display:none;">
		{{ render_field(form.mname, class_="col-sm-6") }}
		{{ render_field(form.rname, class_="col-sm-6") }}
	</div>

	{{ render_field(form.value) }}

	<div class="py-3"></div>

	{{ render_submit_field(form.submit) }}
</form>

{% if is_edit %}
<form method="POST"
		action="{{ url_for('website.domain_record_delete', domain=domain, hostname=hostname, record=record) }}"
		style="display:inline;">
	<input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
	<input type="submit" name="delete" value="Delete" class="btn btn-danger">
</form>
{% endif %}

{% endblock %}


{% block scriptextra %}
<script>
	class Plaintext {
		constructor(type, field) {
			this.type = type;
		}
		remove() {}
	}

	class TableWidget {
		constructor(type, field, struct, container_key) {
			this.type = type;
			this.struct = struct;
			this.field = field;
			this.container_key = container_key || "value";
			this.single_element = (Object.keys(struct).length == 1) ? Object.keys(struct)[0] : null;
			this.set_data(this.get_data());
			this.field.hide();
			this.build();
		}

		build() {
			this.buildTable();
			this.buildInputs();
		}

		buildTable() {
			var field = this.field;

			field.parent().find(".table").remove();
			this.acc = field.parent().append("<table class='table'><tr>" +
				Object.keys(this.struct).map((x) => { return "<th>" + x + "</th>"}).join("") +
				"<th></th></tr></table>").find(".table");

			var rows = this.get_data();
			for (let i = 0; i < rows.length; i++) {
				let row = rows[i];
				this.acc.append("<tr>" +
					Object.keys(this.struct)
						.map((key) => row[key])
						.map((x) => "<td>" + x + "</td>")
						.join("") +
						"<td><button data-i=" + i + " class='delete-row btn btn-danger btn-sm' type='button'>X</button></td>" +
					"</tr>");
			}

			var me = this;
			this.acc.find(".delete-row").click(function() {
				me.delete_row($(this).attr("data-i"));
			});
		}

		buildInputs() {
			this.field.parent().find("table.input").remove();
			this.enter = this.field.parent().append("<table class='input mt-4'><tr></tr></table>").find(".mt-4");
			var input_contain = this.enter.find("tr");

			this.inputs = {};

			for (var key in this.struct) {
				input_contain.append("<td><input id='e"+ key + "' class='form-control' " + ((this.struct[key] == Number) ? "type='number' " : "") +
						"placeholder='" + key + "'><td>");
				this.inputs[key] = input_contain.find("#e" + key);
			}
			input_contain.append("<td class='w-1'><button class='add-row btn btn-primary' type='button'>Add</button></td>")
			this.add   = input_contain.find(".add-row");
			this.add.click(this.on_add.bind(this));
		}

		get_raw_data() {
			try {
				return JSON.parse(this.field.val())[this.container_key];
			} catch {
				return [];
			}
		}

		set_raw_data(data) {
			var val = {};
			val[this.container_key] = data;
			this.field.val(JSON.stringify(val));
		}

		get_data() {
			var retval = this.get_raw_data();
			if (this.single_element) {
				return retval.map((x) => { return { [this.single_element]: x } });
			} else {
				return retval;
			}
		}

		set_data(data) {
			if (this.single_element) {
				data = data.map((x) => x[this.single_element]);
			}
			this.set_raw_data(data);
		}

		on_add() {
			var ret = {};
			for (let key in this.inputs) {
				ret[key] = this.inputs[key].val();
				if (this.struct[key] == Number) {
					ret[key] = parseInt(ret[key]);
				}
			}

			var rows = this.get_data();
			rows.push(ret);
			this.set_data(rows);
			this.build();
		}

		delete_row(i) {
			var rows = this.get_data();
			rows.splice(i, 1);
			this.set_data(rows);
			this.build();
		}

		remove() {
			this.acc.remove();
			this.enter.remove();
			this.field.show();
		}
	}

	class SOAWidget extends TableWidget {
		constructor(type, field) {
			super(type, field, { time: Number }, "times");

			$(".soa").show();
		}
		remove() {
			super.remove();
			$(".soa").hide();
		}
	}

	(function() {
		var field  = $("#value");
		var etype  = $("#type");
		var widget = null;

		function init() {
			var type = etype.val()
			if (widget) {
				if (widget.type == type) {
					return;
				}

				widget.remove();
				field.val("");
			}

			if (type == "A" || type == "AAAA") {
				widget = new TableWidget(type, field, { ip: String });
			} else if (type == "CNAME" || type == "TXT") {
				widget = new Plaintext(type, field);
			} else if (type == "CAA") {
				widget = new TableWidget(type, field, { flags: Number, tag: String, value: String });
			} else if (type == "MX") {
				widget = new TableWidget(type, field, { domain: String, preference: Number });
			} else if (type == "NAPTR") {
				widget = new TableWidget(type, field, { order: Number, preference: Number, flags: String, service: String, regexp: String, replacement: String });
			} else if (type == "NS") {
				widget = new TableWidget(type, field, { domain: String });
			} else if (type == "SOA") {
				widget = new SOAWidget(type, field);
			} else if (type == "SRV") {
				widget = new TableWidget(type, field, { priority: Number, weight: Number, port: Number, target: String });
			} else {
				alert("Unknown type! " + type);
			}
		}

		etype.change(init);
		init();
	})();
</script>
{% endblock %}

api/templates/records.html
{% extends "base.html" %}

{% block title %}
Welcome
{% endblock %}

{% block content %}

{% if root_record and not root_record.live %}
	<div class="alert alert-info">
		<h2>Setup needed</h2>

		<p>
			Please add the following nameservers to your domain's registration:
		</p>

		<ul>
			<li><pre>ns1.uh-dns.com.</pre></li>
			<li><pre>ns2.uh-dns.com.</pre></li>
		</ul>

		<p>
			Then click "Check"
		</p>

		<form method="POST" action="{{ url_for('website.domain_check', domain=domain) }}">
			<input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
			<input type="submit" name="check" value="Check" class="btn btn-primary">
		</form>
	</div>
{% endif %}

<a class="float-right btn btn-primary" href="{{ url_for('website.domain_record_newedit', domain=domain) }}">New</a>
<h1>Records</h1>

{% if not root_record %}
	<div class="alert alert-danger">
		<a class="float-right btn btn-sm btn-danger" href="{{ url_for('website.domain_record_newedit', domain=domain, hostname=domain) }}">
			Create Record
		</a>

		<b>Unable to find a root record!</b>
	</div>
{% endif %}


<div class="list-group">
	{% for r in records %}
		<div href="#" class="list-group-item">
			{{ r.domain }}

			<div class="float-right">
				{% for type in getRTypes(r) %}
					{% if type.name in ['A','AAAA','CNAME'] %}
						{% set btype="info" %}
					{% elif type.name in ['MX'] %}
						{% set btype="warning" %}
					{% elif type.name in ['CAA', 'NAPTR', 'NS', 'SOA'] %}
						{% set btype="success" %}
					{% else %}
						{% set btype="secondary" %}
					{% endif %}

					<a class="btn btn-sm btn-{{ btype }}" href="{{ url_for('website.domain_record_newedit', domain=domain, record=type.name, hostname=r.domain) }}">
						{{ type.name }}
					</a>
				{% endfor %} |

				<a class="btn btn-sm btn-primary" href="{{ url_for('website.domain_record_newedit', domain=domain, hostname=r.domain) }}">Add</a>
				<form method="POST"
						action="{{ url_for('website.domain_record_delete', domain=domain, hostname=r.domain) }}"
						style="display:inline;">
					<input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
					<input type="submit" name="delete" value="Delete" class="btn btn-sm btn-danger">
				</form>
			</div>
		</div>
	{% endfor %}
</div>
{% endblock %}

api/templates/sites.html
{% extends "base.html" %}

{% block title %}
Welcome
{% endblock %}

{% block content %}
<h1>Sites</h1>


<div class="list-group">
	{% for d in domains %}
		<a href="{{ url_for('website.site_records', domain=d) }}"
				class="list-group-item list-group-item-action">
			{{ d }}
		</a>
	{% else %}
		<div class="list-group-item"><i>No sites found.</i></div>
	{% endfor %}
</div>
{% endblock %}
<!doctype html>